[build]
	publish = "dist/"
	[build.processing]
		skip_processing = false
	[build.processing.css]
		bundle = true
		minify = true
	[build.processing.js]
		bundle = true
		minify = true
	[build.processing.html]
		pretty_urls = true
	[build.processing.images]
		compress = true
[context.deploy-preview]
	command = 'echo -e "/*\n  Basic-Auth: $BASIC_AUTH_ID:$BASIC_AUTH_PASS" > dist/_headers'
[context.branch-deploy]
	command = 'echo -e "/*\n  Basic-Auth: $BASIC_AUTH_ID:$BASIC_AUTH_PASS" > dist/_headers'
[[redirects]]
	from = "/new_release/:nid"
	to = "/new_release.html"
	status = 200
[[redirects]]
	from = "/media_compass/:nid"
	to = "/media_compass.html"
	status = 200